server:
  port: 8080

logging:
  config: classpath:logback-spring-dev.xml
  level:
    org:
      hibernate:
        SQL: DEBUG

#스웨거 설정
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 환경 변수
datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: ${DATABASE_DRIVERCLASSNAME}
  url1: ${DATABASE_URL1}
  url2: ${DATABASE_URL2}

jwt:
  secret-key-source: dGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLXdpdGgtbWluaW11bS0zMi1ieXRlcw==